### ISSUE TITLE
Review / Rework

### ISSUE THREAD

**Issue by sstitz** [P4ntomime/elektronik-2#6]
### ToDo

Review of Elektronik 2 summary

## High Priority
- [x] Review of document (typo corrections, general feedback, style guide)
- [x] Check section splitting (according to comments in code (currently section 11 Analoge Filter)
- [x] If sections are splitted: rework on following sub(sub)sections so that document structure makes sence again

## Low Priority
- [x] Fix warnings
- [x] Formatting (some tables, according to TODOs in code)
